server:
  port: 8081

spring:
  application:
    name: web
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1000
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  hystrix:
    enabled: true

